### ISSUE TITLE
Searching a log file

### ISSUE THREAD

**Issue by NauiDiver** [woanware/LogViewer#10]
I have a log file with 3,808,479 lines in it. I am using the search function for text [Thread-6823]. I see at the bottom of the screen that it found Matched 44 lines (Search Terms: 1).... however, it does not inform me which line the results are on nor does it allow me to "Go To" any matched lines.

**Comment by woanware** [comment]
You figured it out then?

**Comment by NauiDiver** [comment]
I did! Was missing reading the help me pdf. Awesome app!
