### ISSUE TITLE
Enhancement requests

### ISSUE THREAD

**Issue by CdtDelta** [woanware/LogViewer#3]
I'd like to see the following enhancements:

1) The ability, within the search results window, to turn on looking at x number of lines before and/or after the search hit (like the grep -a and -b switches).

2) The ability to go to a specific line number within the file that's opened.

3) The ability to click on a hit within the search results, and then clear the filter but stay on the same line that was already selected (versus going back to the top of the file).

**Comment by woanware** [comment]
1) The ability, within the search results window, to turn on looking at x number of lines before and/or after the search hit (like the grep -a and -b switches). - DONE

**Comment by intellectualkid** [comment]
hi woanware!
i want to contribute in this project . could you please list down enhancements or issues.

**Comment by woanware** [comment]
All of the enhancements are listed in the first message, and all are being
developed.

Feel free to add your own enhancement ideas as issues or you can fork the
project

**Comment by woanware** [comment]
2) The ability to go to a specific line number within the file that's opened. - DONE

**Comment by woanware** [comment]
3) The ability to click on a hit within the search results, and then clear the filter but stay on the same line that was already selected (versus going back to the top of the file). - DONE (Added go to first and last lines as well)
