### ISSUE TITLE
Reference woanware missing

### ISSUE THREAD

**Issue by smygarn** [woanware/LogViewer#5]
Some errors while compiling the source. Most important is:

- The type or namespace name 'woanware' could not be found

**Comment by woanware** [comment]
If you can supply the full error log then I can look into it

**Comment by smygarn** [comment]
I got it to work when I added ref. to your Utility.dll manually in VS.

**Comment by VladimirRybalko** [comment]
I've faced with the same issue. Seems that **.csproj** file has the incorrect reference to Utility.dll.
I'm going to add a pull request soon.

**Comment by woanware** [comment]
Fixed by @VladimirRybalko
