### ISSUE TITLE
Feature Request: Load Multiple Files

### ISSUE THREAD

**Issue by bridgeythegeek** [woanware/LogViewer#8]
A common situation is having multiple log files to search through. For example, a folder of IIS logs (one log per day): I'd have to open each file in a new instance and repeat the work.

If multiple files could be opened in the same instance of the application one could easily search through all the files in one go.

Perhaps multiple tabs or concatenating the files into one big file (treating them all as one big file).

**Comment by woanware** [comment]
Gee, you don't want much do you! :-) Well at least someone other than me is
using it!

**Comment by woanware** [comment]
![2019-06-28 14_19_48-LogViewer](https://user-images.githubusercontent.com/1075956/60344999-e1e94b00-99af-11e9-838b-274a63bc8c57.png)

**Comment by woanware** [comment]
Completed.
